#theme: minima
remote_theme: pages-themes/modernist@v0.2.0
author: Andrés Alcarraz<alcarraz@gmail.com>
description: An electrical and software engineer that enjoys solving problems and helping others.

google_analytics: G-29VKRNWX58

title: Andrés Alcarraz

photo: /img/andres.png
