#theme: minima
remote_theme: pages-themes/modernist@v0.2.0
author: Andrés Alcarraz<alcarraz@gmail.com>
description: An electrical and software engineer that enjoys solving problems and helping others.

google_analytics: G-29VKRNWX58

title: Andrés Alcarraz

photo: /img/andres.png

plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Mailchimp configuration
mailchimp:
  datacenter: "us7"
  user_id: "716182c58440cfff87dc0b1fb"
  audience_id: "3f2fbcbfa9"
  form_id: "00c433e0f0"
  subdomain: "github"

# _config.yml
defaults:
  - scope:
      path: "" # An empty string indicates all files
    values:
      layout: "default" # Sets 'default' as the layout for all files
#  - scope:
#      path: "_posts"
#      type: "posts"
#    values:
#      layout: "post" # Sets 'post' as the layout for all posts
#  - scope:
#      path: "my-specific-folder"
#    values:
#      layout: "custom-layout" # Sets 'custom-layout' for files in 'my-specific-folder'
